# Generated by Django 5.0.6 on 2024-08-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_profile', '0003_rename_desc_profile_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_profile_image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media'),
        ),
    ]
