# Generated by Django 5.0.6 on 2024-08-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('radio', models.CharField(max_length=50)),
                ('rnumber', models.IntegerField(blank=True, default=0, null=True)),
                ('feed_message', models.TextField()),
            ],
        ),
    ]
