# Generated by Django 5.0.6 on 2024-09-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drushti_feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedback',
            old_name='radio',
            new_name='satisfied',
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='rnumber',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
