# Generated by Django 5.0.6 on 2024-09-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drushti_feedback', '0002_rename_radio_userfeedback_satisfied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='rnumber',
            field=models.IntegerField(null=True),
        ),
    ]
