# Generated by Django 5.0.6 on 2024-09-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Analytics_icon', models.FileField(default=None, max_length=250, null=True, upload_to='drushti_services/')),
                ('Analytics_title', models.CharField(max_length=100)),
                ('Analytics_des', models.TextField()),
                ('Analytics_btn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', models.TextField()),
                ('faq_ans', models.TextField()),
            ],
        ),
    ]
