# Generated by Django 5.0.6 on 2024-11-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_slid_img', models.FileField(blank=True, max_length=250, null=True, upload_to='ourClient/')),
            ],
        ),
    ]
