# Generated by Django 5.0.6 on 2024-11-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ourclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourclient',
            name='exp_slid_img',
        ),
        migrations.AddField(
            model_name='ourclient',
            name='image',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='ourClient/'),
        ),
    ]
