# Generated by Django 5.0.6 on 2024-07-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page_title', models.CharField(max_length=100)),
                ('Page_subtitle', models.CharField(max_length=100)),
                ('Suggestion_title', models.CharField(max_length=50)),
                ('Plan_title', models.CharField(max_length=50)),
                ('Plan_amount', models.CharField(max_length=50)),
                ('Plan_highlight1', models.CharField(max_length=50)),
                ('Plan_highlight2', models.CharField(max_length=50)),
                ('Plan_highlight3', models.CharField(max_length=50)),
                ('Plan_highlight4', models.CharField(max_length=50)),
                ('Plan_highlight5', models.CharField(max_length=50)),
                ('Plan_btn', models.CharField(max_length=50)),
            ],
        ),
    ]
