# Generated by Django 5.0.6 on 2024-07-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_drushtiserplans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesplans',
            name='Page_subtitle',
        ),
        migrations.RemoveField(
            model_name='servicesplans',
            name='Page_title',
        ),
    ]
