# Generated by Django 5.0.6 on 2024-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_drushtiserplans', '0002_remove_servicesplans_page_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page_title', models.CharField(max_length=100)),
                ('Page_subtitle', models.CharField(max_length=50)),
            ],
        ),
    ]
