# Generated by Django 5.0.6 on 2024-07-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_drushtiserplans', '0003_plans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plans',
        ),
    ]
