# Generated by Django 5.0.6 on 2024-07-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_drushtiserplans', '0004_delete_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesplans',
            name='Plan_Condition1',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesplans',
            name='Plan_Condition2',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesplans',
            name='Plan_Condition3',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesplans',
            name='Plan_Condition4',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesplans',
            name='Plan_Condition5',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesplans',
            name='Plan_des_title',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesplans',
            name='close_btn',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
