# Generated by Django 5.0.6 on 2024-07-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_drushtiserplans', '0006_plandescription_remove_servicesplans_plan_condition1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandescription',
            name='Plan_Condition1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plandescription',
            name='Plan_Condition2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plandescription',
            name='Plan_Condition3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plandescription',
            name='Plan_Condition4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plandescription',
            name='Plan_Condition5',
            field=models.TextField(),
        ),
    ]
