# Generated by Django 5.0.6 on 2024-07-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_drushtiserplans', '0007_alter_plandescription_plan_condition1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandescription',
            name='close_btn',
        ),
    ]
