# Generated by Django 5.0.6 on 2024-08-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_drushtiserplans', '0008_remove_plandescription_close_btn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesplans',
            name='Plan_amount',
            field=models.FloatField(),
        ),
    ]
