# Generated by Django 5.0.6 on 2024-07-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_pass',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
