# Generated by Django 5.0.6 on 2024-11-12 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('amountLow', models.IntegerField(default=0)),
                ('amountHigh', models.IntegerField(default=0)),
                ('applycount', models.IntegerField(default=0)),
                ('lastDateToApply', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateApplications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('yearOfExt', models.IntegerField()),
                ('dataset', models.FileField(upload_to='media')),
                ('status', models.CharField(choices=[('pandding', 'pandding'), ('selected', 'selected')], default='pandding', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myanalyst.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='SelectCandidateJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myanalyst.candidateapplications')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myanalyst.jobpost')),
            ],
        ),
    ]
