# Generated by Django 5.0.6 on 2024-07-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drushti_contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_title', models.CharField(max_length=20)),
                ('cont_meg', models.CharField(max_length=50)),
                ('my_location', models.CharField(max_length=100)),
                ('my_phone', models.CharField(max_length=50)),
                ('my_email', models.CharField(max_length=50)),
                ('cont_btn', models.CharField(max_length=20)),
            ],
        ),
    ]
