# Generated by Django 5.0.6 on 2024-07-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drushti_contact', '0002_my_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_contact',
            name='location_des',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='my_contact',
            name='my_location',
            field=models.CharField(max_length=50),
        ),
    ]
