# Generated by Django 5.0.6 on 2024-07-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drushti_contact', '0003_my_contact_location_des_alter_my_contact_my_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_contact',
            name='cont_meg',
            field=models.CharField(max_length=500),
        ),
    ]
