# Generated by Django 5.0.6 on 2024-07-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drushti_contact', '0004_alter_my_contact_cont_meg'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_contact',
            name='my_email1',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_contact',
            name='my_phone1',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
